/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: youyuan20.c                                           *
* Font:        ??                                                  *
* Height:      27                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  27                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\wang\Desktop\??????.txt          *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontyouyuan20;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_4EBA[108] = { /* code 4EBA */
  ________,________,________,________,
  ________,________,________,________,
  ________,_____X__,________,________,
  ________,_____X__,________,________,
  ________,_____X__,________,________,
  ________,_____X__,________,________,
  ________,_____X__,________,________,
  ________,_____X__,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,____XXXX,________,________,
  ________,____X__X,________,________,
  ________,____X__X,________,________,
  ________,___XX___,X_______,________,
  ________,___X____,X_______,________,
  ________,__XX____,_X______,________,
  ________,__X_____,_XX_____,________,
  ________,_X______,__X_____,________,
  ________,XX______,__XX____,________,
  _______X,X_______,___XX___,________,
  ______XX,________,____X___,________,
  _____XX_,________,_____X__,________,
  ____XX__,________,_____XX_,________,
  __XXX___,________,______XX,________,
  _XX_____,________,________,XX______,
  ________,________,________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_51B7[108] = { /* code 51B7 */
  ________,________,________,________,
  ________,________,________,________,
  ________,_______X,X_______,________,
  __X_____,______XX,XX______,________,
  __X_____,_____XX_,_XX_____,________,
  __XX____,____XX__,__XX____,________,
  ___X____,___XX___,___XX___,________,
  ___XX___,__XX____,____XX__,________,
  ____X___,_XX___X_,_____XXX,________,
  ____X__X,XX____XX,_______X,X_______,
  ____X_XX,_______X,X_______,XX______,
  ________,________,XX______,________,
  ________,________,_XX_____,________,
  ________,________,________,________,
  ______X_,XXXXXXXX,XXXXXX__,________,
  _____XX_,XXXXXXXX,XXXXXXX_,________,
  _____X__,________,_____XX_,________,
  _____X__,________,_____XX_,________,
  ____XX__,________,____XX__,________,
  ____X___,___X____,___XX___,________,
  ____X___,___XX___,___X____,________,
  ___XX___,____XX__,__XX____,________,
  ___X____,_____XXX,_XX_____,________,
  __XX____,_______X,XX______,________,
  _XX_____,________,XX______,________,
  ________,________,_XX_____,________,
  ________,________,__XX____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_5236[108] = { /* code 5236 */
  ________,________,________,________,
  ________,________,________,________,
  ____X___,XX______,________,________,
  ____X___,XX______,_______X,________,
  ____X___,XX______,___X___X,________,
  ___XXXXX,XXXXXXXX,___X___X,________,
  ___XXXXX,XXXXXXXX,X__X___X,________,
  __XX____,XX______,___X___X,________,
  __X_____,XX______,___X___X,________,
  __X_____,XX______,___X___X,________,
  _XXXXXXX,XXXXXXXX,XX_X___X,________,
  ________,XX______,___X___X,________,
  ________,XX______,___X___X,________,
  ________,XX______,___X___X,________,
  ________,XX______,___X___X,________,
  __XXXXXX,XXXXXXXX,___X___X,________,
  __XX____,XX_____X,___X___X,________,
  __X_____,XX_____X,___X___X,________,
  __X_____,XX_____X,___X___X,________,
  __X_____,XX_____X,___X___X,________,
  __X_____,XX_____X,___X___X,________,
  __X_____,XX_____X,___X___X,________,
  __X_____,XX_____X,_______X,________,
  __X_____,XX_____X,_______X,________,
  __X_____,XX_XXXXX,_______X,________,
  __X_____,XX__XXX_,__XXXXXX,________,
  ________,________,_____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_52A0[108] = { /* code 52A0 */
  ________,________,________,________,
  ________,________,________,________,
  ______X_,________,________,________,
  ______X_,________,________,________,
  ______X_,________,XXXXXXXX,________,
  ______X_,_______X,X______X,X_______,
  _XXXXXXX,XXXXX__X,X______X,X_______,
  ______X_,____X__X,X______X,X_______,
  ______X_,____X__X,X______X,X_______,
  ______X_,____X__X,X______X,X_______,
  ______X_,____X__X,X______X,X_______,
  ______X_,____X__X,X______X,X_______,
  ______X_,____X__X,X______X,X_______,
  ______X_,____X__X,X______X,X_______,
  _____XX_,____X__X,X______X,X_______,
  _____XX_,____X__X,X______X,X_______,
  _____X__,____X__X,X______X,X_______,
  _____X__,____X__X,X______X,X_______,
  ____XX__,____X__X,X______X,X_______,
  ____X___,____X__X,X______X,X_______,
  ____X___,____X__X,X______X,X_______,
  ___XX___,____X__X,X______X,X_______,
  ___X____,____X__X,X______X,X_______,
  __XX____,____X__X,X______X,X_______,
  __X_____,____X__X,X______X,X_______,
  _X____XX,XXXXX___,XXXXXXXX,________,
  ________,_X______,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_65E0[108] = { /* code 65E0 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ___XXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,____X___,________,________,
  ________,____X___,________,________,
  ________,____X___,________,________,
  ________,____X___,________,________,
  ________,____X___,________,________,
  ________,____X___,________,________,
  ________,___XX___,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ________,___X__XX,________,________,
  ________,___X__XX,________,________,
  ________,___X__XX,________,________,
  ________,__XX__XX,________,________,
  ________,__X___XX,________,________,
  ________,_XX___XX,________,________,
  ________,_X____XX,________,________,
  ________,XX____XX,________,XX______,
  _______X,X_____XX,________,XX______,
  ______XX,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  ____XX__,______XX,________,XX______,
  __XXX___,______XX,________,X_______,
  _XXX____,_______X,XXXXXXXX,X_______,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_6709[108] = { /* code 6709 */
  ________,________,________,________,
  ________,________,________,________,
  ________,___XX___,________,________,
  ________,___X____,________,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ________,_XX_____,________,________,
  ________,XX______,________,________,
  _______X,X_______,________,________,
  ______XX,XXXXXXXX,XXXXXXX_,________,
  ____XXX_,________,______X_,________,
  ___XXXX_,________,______X_,________,
  _XXX_XX_,________,______X_,________,
  XX___XX_,________,______X_,________,
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  _____XX_,________,______X_,________,
  _____XX_,________,______X_,________,
  _____XX_,________,______X_,________,
  _____XX_,________,______X_,________,
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  _____XX_,________,______X_,________,
  _____XX_,________,______X_,________,
  _____XX_,________,______X_,________,
  _____XX_,________,______X_,________,
  _____XX_,________,______X_,________,
  _____XX_,________,_XXXXXX_,________,
  ________,________,____X___,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_6E7F[108] = { /* code 6E7F */
  ________,________,________,________,
  ________,________,________,________,
  ___X____,________,________,________,
  ___XX___,_XXXXXXX,XXXXXXXX,________,
  ____XX__,XX______,_______X,________,
  _____XX_,XX______,_______X,________,
  _____XX_,XX______,_______X,________,
  ______XX,XXXXXXXX,XXXXXXXX,________,
  ________,XX______,_______X,________,
  _XX_____,XX______,_______X,________,
  _XXX____,XX______,_______X,________,
  ___XX___,XX______,_______X,________,
  ____XX__,_XXXXXXX,XXXXXXXX,________,
  _____X__,_____X__,__X_____,________,
  ________,_____X__,__X_____,________,
  _____X_X,X____X__,__X____X,________,
  _____X__,X____X__,__X____X,________,
  _____X__,XX___X__,__X___XX,________,
  ____XX__,_X___X__,__X___X_,________,
  ____X___,_XX__X__,__X__XX_,________,
  ____X___,_XX__X__,__X_XX__,________,
  ___XX___,__X__X__,__X_X___,________,
  ___X____,_____X__,__X_____,________,
  ___X____,_____X__,__X_____,________,
  __XX____,_____X__,__X_____,________,
  __X___XX,XXXXXXXX,XXXXXXXX,XX______,
  __X_____,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_70ED[108] = { /* code 70ED */
  ________,________,________,________,
  ________,________,________,________,
  ______X_,________,X_______,________,
  ______X_,________,X_______,________,
  ______X_,________,X_______,________,
  __XXXXXX,XXXXXXXX,XXXXXX__,________,
  __XXXXXX,XX______,X____X__,________,
  ______X_,________,X____X__,________,
  ______X_,_X__X___,X____X__,________,
  ______X_,XX___X_X,X____X__,________,
  ______XX,_____XXX,X____X__,________,
  ____XXX_,______XX,_____X__,________,
  __XXX_X_,______XX,_____X__,________,
  _XX___X_,______XX,_____XX_,_X______,
  ______X_,______XX,X____XX_,_X______,
  ______X_,_____XX_,X____XX_,_X______,
  ______X_,_____X__,_X____X_,_X______,
  ______X_,____XX__,_XX___X_,_X______,
  __XXXXX_,___XX___,__X___X_,XX______,
  ____XXX_,___X____,______XX,X_______,
  ________,________,X____X__,________,
  _____X__,__X_____,X____XX_,________,
  ____XX__,__X_____,XX____X_,________,
  ___XX___,__X_____,XX____XX,________,
  ___X____,__XX____,_X_____X,X_______,
  __XX____,__XX____,_XX_____,X_______,
  _XX_____,___X____,_XX_____,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_9664[108] = { /* code 9664 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,XX______,________,
  __XXXXXX,_______X,XXX_____,________,
  __X____X,______XX,__XX____,________,
  __X____X,_____XX_,___XX___,________,
  __X____X,____XX__,____XX__,________,
  __X___XX,___XX___,______XX,________,
  __X___X_,_XXX____,_______X,X_______,
  __X__XX_,_X______,________,XX______,
  __X__X__,__XXXXXX,XXXXXXXX,________,
  __X__XX_,________,XX______,________,
  __X___X_,________,XX______,________,
  __X____X,________,XX______,________,
  __X____X,X_______,XX______,________,
  __X_____,X_XXXXXX,XXXXXXXX,X_______,
  __X_____,XX______,XX______,________,
  __X_____,X_______,XX______,________,
  __X_X__X,X___X___,XX___X__,________,
  __X_XXXX,___X____,XX___XX_,________,
  __X_____,__XX____,XX____XX,________,
  __X_____,_XX_____,XX_____X,________,
  __X_____,XX______,XX_____X,X_______,
  __X____X,X_______,XX______,X_______,
  __X_____,________,XX______,XX______,
  __X_____,___XXX_X,X_______,________,
  ________,_____XXX,X_______,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontyouyuan20_CharInfo[9] = {
   {  28,  28,  4, acGUI_Fontyouyuan20_4EBA } /* code 4EBA */
  ,{  28,  28,  4, acGUI_Fontyouyuan20_51B7 } /* code 51B7 */
  ,{  28,  28,  4, acGUI_Fontyouyuan20_5236 } /* code 5236 */
  ,{  28,  28,  4, acGUI_Fontyouyuan20_52A0 } /* code 52A0 */
  ,{  28,  28,  4, acGUI_Fontyouyuan20_65E0 } /* code 65E0 */
  ,{  28,  28,  4, acGUI_Fontyouyuan20_6709 } /* code 6709 */
  ,{  28,  28,  4, acGUI_Fontyouyuan20_6E7F } /* code 6E7F */
  ,{  28,  28,  4, acGUI_Fontyouyuan20_70ED } /* code 70ED */
  ,{  28,  28,  4, acGUI_Fontyouyuan20_9664 } /* code 9664 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop9 = {
   0x9664 /* first character */
  ,0x9664 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[  8] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop8 = {
   0x70ED /* first character */
  ,0x70ED /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[  7] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop7 = {
   0x6E7F /* first character */
  ,0x6E7F /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[  6] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop6 = {
   0x6709 /* first character */
  ,0x6709 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[  5] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop5 = {
   0x65E0 /* first character */
  ,0x65E0 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[  4] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop4 = {
   0x52A0 /* first character */
  ,0x52A0 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[  3] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop3 = {
   0x5236 /* first character */
  ,0x5236 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[  2] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop2 = {
   0x51B7 /* first character */
  ,0x51B7 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[  1] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop1 = {
   0x4EBA /* first character */
  ,0x4EBA /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[  0] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontyouyuan20 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,27 /* height of font  */
  ,27 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontyouyuan20_Prop1}
  ,23 /* Baseline */
  ,12 /* Height of lowercase characters */
  ,19 /* Height of capital characters */
};



/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontyouyuan16;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_51B7[ 32] = { /* code 51B7 */
  ________,________,
  ________,________,
  _X______,XXX_____,
  _X_____X,___X____,
  __X___X_,____X___,
  __X__X__,X____X__,
  ____X___,_X____X_,
  ________,__X_____,
  ________,________,
  ___X_XXX,XXXXXX__,
  ___X____,____X___,
  __X_____,____X___,
  __X___XX,___X____,
  __X_____,X_X_____,
  _X______,_X______,
  ________,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_5236[ 32] = { /* code 5236 */
  ________,________,
  _____X__,________,
  __X__X__,______X_,
  __X__X__,___X__X_,
  _X_XXXXX,X__X__X_,
  _X___X__,___X__X_,
  _XXXXXXX,XXXX__X_,
  _____X__,___X__X_,
  _____X__,___X__X_,
  __XXXXXX,X__X__X_,
  _X___X__,_X_X__X_,
  _X___X__,_X_X__X_,
  _X___X__,_X_X__X_,
  _X___X__,_X____X_,
  _X___X__,_X____X_,
  _X___XXX,X__XXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_52A0[ 32] = { /* code 52A0 */
  ________,________,
  ___X____,________,
  ___X____,________,
  ___X____,_XXXXXX_,
  _XXXXXXX,_X____X_,
  ___X___X,_X____X_,
  ___X___X,_X____X_,
  ___X___X,_X____X_,
  ___X___X,_X____X_,
  ___X___X,_X____X_,
  ___X___X,_X____X_,
  __X____X,_X____X_,
  __X____X,_X____X_,
  __X____X,_X____X_,
  _X_____X,_X____X_,
  X___XXX_,_XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_6E7F[ 32] = { /* code 6E7F */
  ________,________,
  ________,________,
  __X__XXX,XXXXXX__,
  ___X_X__,_____X__,
  ___XXX__,_____X__,
  _____XXX,XXXXXX__,
  _X___X__,_____X__,
  __X__XXX,XXXXXX__,
  ___X___X,__X_____,
  __X_X__X,__X_____,
  ___X_X_X,__X__X__,
  __X__X_X,__X__X__,
  __X__X_X,__X_X___,
  __X___XX,__X_____,
  _X_____X,__X_____,
  _X_XXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_70ED[ 32] = { /* code 70ED */
  ________,________,
  ________,_X______,
  ___X____,_X______,
  _XXXXX_X,XXXXX___,
  ___X____,_X__X___,
  ___X_X_X,_X__X___,
  ___XX___,XX__X___,
  __XX____,XX__X___,
  _X_X____,XX__X_X_,
  ___X____,XX__X_X_,
  ___X___X,__X__XX_,
  _XXX___X,__X__XX_,
  ________,_X__X___,
  __X___X_,_X___X__,
  __X___X_,__X__X__,
  _X____X_,__X___X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_8212[ 32] = { /* code 8212 */
  ________,________,
  ________,________,
  ___XXX__,XXXXXXX_,
  __X___XX,_____X__,
  XX_____X,_X___X__,
  __XXXXX_,X_X_X___,
  ____X___,___X____,
  ____X___,___X____,
  _XXXXXXX,XXXXXXX_,
  ____X___,___X__X_,
  ___XXX__,___X__X_,
  _XX___XX,___X__X_,
  _X_____X,___X_X__,
  _X_____X,___X____,
  _X_____X,___X____,
  __XXXXX_,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_9002[ 32] = { /* code 9002 */
  ________,________,
  ________,________,
  __X___XX,XXXXXX__,
  __X_____,_X______,
  ___X____,_X______,
  _____XXX,XXXXXXX_,
  _XX_____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X__XX,XXXXX___,
  ___X__X_,_____X__,
  ___X__X_,_____X__,
  ___X__X_,_____X__,
  ___X__XX,XXXXX___,
  __X_X___,________,
  _X___XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_9664[ 32] = { /* code 9664 */
  ________,________,
  ________,________,
  _XXXX___,_XX_____,
  _X__X___,X__X____,
  _X__X__X,____XX__,
  _X_X_XX_,______X_,
  _X_X__XX,XXXXXX__,
  _X_X____,_X______,
  _X__X___,_X______,
  _X__X_XX,XXXXXXX_,
  _X__X___,_X______,
  _XX_X__X,_X__X___,
  _X_X__X_,_X___X__,
  _X___X__,_X____X_,
  _X__X___,_X____X_,
  _X_____X,XX______};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontyouyuan16_CharInfo[8] = {
   {  16,  16,  2, acGUI_Fontyouyuan16_51B7 } /* code 51B7 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_5236 } /* code 5236 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_52A0 } /* code 52A0 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_6E7F } /* code 6E7F */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_70ED } /* code 70ED */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_8212 } /* code 8212 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_9002 } /* code 9002 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_9664 } /* code 9664 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop8 = {
   0x9664 /* first character */
  ,0x9664 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[  7] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop7 = {
   0x9002 /* first character */
  ,0x9002 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[  6] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop6 = {
   0x8212 /* first character */
  ,0x8212 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[  5] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop5 = {
   0x70ED /* first character */
  ,0x70ED /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[  4] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop4 = {
   0x6E7F /* first character */
  ,0x6E7F /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[  3] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop3 = {
   0x52A0 /* first character */
  ,0x52A0 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[  2] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop2 = {
   0x5236 /* first character */
  ,0x5236 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[  1] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop1 = {
   0x51B7 /* first character */
  ,0x51B7 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[  0] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontyouyuan16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontyouyuan16_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};



